version: '3'
services:
  mongodb:
    image: mongo:3.6.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  app:
    build: .
    environment:
      NEWSAPI_KEY: ${NEWSAPI_KEY}
      MONGO_USER: admin
      MONGO_PASS: admin
    depends_on:
      - "mongodb"
